services:
  request:
    synthetic:                      true
  kladr:
    class:      n3b\Bundle\Kladr\Service\Kladr
    arguments:
      em:       '@doctrine.orm.entity_manager'
      request:  '@request'