n3b_kladr_region:
  pattern: /region/{query}
  defaults: { _controller: kladr:getRegions }

n3b_kladr_street:
  pattern: /street/{region}/{query}
  defaults: { _controller: kladr:getStreets }
  requirements:
    region: \d{10,11}

n3b_kladr_ems_to:
  pattern: /emsTo/{region}/{weight}
  defaults: { _controller: kladr:getEmsTo }
  requirements:
    region: \d{10,11}
    weight: ([0-9]+(\.[0-9]+)?)

n3b_kladr_adds_by_street_code:
  pattern: /adds_by_code/{code}
  defaults: { _controller: kladr:getAddsByCode, code: '000000000000000' }
  requirements:
    code: \d{15}
